// List of words with Turkish and English meanings, and source information
const words = [
    {french: "	Le soleil	",	turkish: "	gunes	",	source: "	Campus 1	/	Unité 1	"},
{french: "	Les nuages	",	turkish: "	bulutlar	",	source: "	Campus 1	/	Unité 1	"},
{french: "	La lune	",	turkish: "	ay	",	source: "	Campus 1	/	Unité 1	"},
{french: "	Les étoiles	",	turkish: "	yildizlar	",	source: "	Campus 1	/	Unité 1	"},
{french: "	Les arbres	",	turkish: "	agaclar	",	source: "	Campus 1	/	Unité 1	"},
{french: "	La fenêtre	",	turkish: "	pencere	",	source: "	Campus 1	/	Unité 1	"},
{french: "	La piscine	",	turkish: "	yuzme havuzu	",	source: "	Campus 1	/	Unité 1	"},
{french: "	Détester	",	turkish: "	nefret etmek	",	source: "	Campus 1	/	Unité 2	"},
{french: "	La trottinette	",	turkish: "	scooter	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Le tatouage	",	turkish: "	tattoo	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Médecin	",	turkish: "	doctor	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Architecte	",	turkish: "	mimar	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Infirmier	",	turkish: "	hemsire	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Ingénieur	",	turkish: "	muhendis	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Journaliste	",	turkish: "	gazeteci	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Policier	",	turkish: "	polis	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Ennuyeux, ennuyeuse	",	turkish: "	sıkıcı	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Utile	",	turkish: "	useful	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Inutile	",	turkish: "	useless	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Facile	",	turkish: "	easy, simple	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Difficile	",	turkish: "	difficult	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Directeur, directrice	",	turkish: "	director	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Acteur, actrice	",	turkish: "	actor	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Présentateur, présentatrice	",	turkish: "	sunucu	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Cuisinier, cuisinière	",	turkish: "	asci	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Intéressant, intéressante	",	turkish: "	İlginç	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Nouveau, nouvelle	",	turkish: "	yeni	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Joli, jolie	",	turkish: "	hos	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Célèbre	",	turkish: "	unlu	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Collègue	",	turkish: "	is arkadasi	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Comité	",	turkish: "	kurul, board	",	source: "	Campus 1	/	Unité 2	"},
{french: "	La montagne	",	turkish: "	dag	",	source: "	Campus 1	/	Unité 2	"},
{french: "	La cascade	",	turkish: "	selale	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Être fatigué, fatiguée	",	turkish: "	yorgun olmak	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Faire de la natation, nager	",	turkish: "	yuzmek	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Une exposition	",	turkish: "	sergi	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Faire de la musique	",	turkish: "	muzik yapmak	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Danser	",	turkish: "	dans etmek	",	source: "	Campus 1	/	Unité 2	"},
{french: "	La danse	",	turkish: "	dans	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Ecrire	",	turkish: "	yazmak	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Une écriture	",	turkish: "	yazi	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Lire	",	turkish: "	okumak	",	source: "	Campus 1	/	Unité 2	"},
{french: "	La lecture	",	turkish: "	okuma	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Marcher	",	turkish: "	yurumek	",	source: "	Campus 1	/	Unité 2	"},
{french: "	La marche	",	turkish: "	yurume	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Nager	",	turkish: "	yuzmek	",	source: "	Campus 1	/	Unité 2	"},
{french: "	La natation	",	turkish: "	yuzme	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Travailler	",	turkish: "	calismak	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Le travail	",	turkish: "	is	",	source: "	Campus 1	/	Unité 2	"},
{french: "	une émission	",	turkish: "	program, gosteri, show	",	source: "	Campus 1	/	Unité 2	"},
{french: "	interroger	",	turkish: "	sormak (to ask), soru (question)	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Moyenne	",	turkish: "	ortalama	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Agréable	",	turkish: "	guzel, hoss, rahat	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Au bord de la mer	",	turkish: "	deniz kenarinda	",	source: "	Campus 1	/	Unité 2	"},
{french: "	Les douze mois de l’année	",	turkish: "	yilin oniki ayi	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Janvier, février, mars, avril, mai, juin, juillet, aout, septembre, octobre, novembre, décembre	",	turkish: "	Ocak, Şubat, Mart, Nisan, Mayıs, Haziran, Temmuz, Ağustos, Eylül, Ekim, Kasım, Aralık,January, February, March, April, May, June, July, August, September, October, November, December	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Les sept jours de la semaine	",	turkish: "	haftanin yedi gunu	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Lundi, mardi, mercredi, jeudi, vendredi, samedi, dimanche	",	turkish: "	Pazartesi, Salı, Çarşamba, Perşembe, Cuma, Cumartesi, Pazar, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Les quatre saisons	",	turkish: "	dort mevsim	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Printemps, été, automne, hiver	",	turkish: "	İlkbahar, yaz, sonbahar, kış, Spring, summer, fall, winter	",	source: "	Campus 1	/	Unité 3	"},
{french: "	La fête civile	",	turkish: "	resmi bayram	",	source: "	Campus 1	/	Unité 3	"},
{french: "	La fête religieuse	",	turkish: "	dini bayram	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Grave	",	turkish: "	sert, hasin	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Partir	",	turkish: "	hareket etmek, yola cikmak	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Revenir	",	turkish: "	geri donmek, come back	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Rentrer	",	turkish: "	geri donmek, return	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Venir	",	turkish: "	gelmek	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Renseignements	",	turkish: "	informations	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Accepter	",	turkish: "	Kabul etmek	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Refuser	",	turkish: "	red etmek	",	source: "	Campus 1	/	Unité 3	"},
{french: "	La glace	",	turkish: "	ice cream	",	source: "	Campus 1	/	Unité 3	"},
{french: "	évidemment	",	turkish: "	tabiki, of course	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Vouloir	",	turkish: "	istemek	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Pouvoir	",	turkish: "	e bilmek	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Devoir	",	turkish: "	zorunda olmak	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Être malade	",	turkish: "	hasta olmak	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Désolée	",	turkish: "	uzgun olmak	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Avoir envie de	",	turkish: "	istekli olmak	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Si	",	turkish: "	olumsuz bir soruya olumlu cevap	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Tourner un film	",	turkish: "	film cevirmek, Shoot a film	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Moi non plus	",	turkish: "	olumsuz bir soruya ayni olumsuz cevap	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Faire du vélo	",	turkish: "	bisiklete binmek	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Le spectacle	",	turkish: "	the show	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Mise en scène	",	turkish: "	sahneye koymak	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Une œuvre	",	turkish: "	sanat eseri	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Le cheval (pl chevaux)	",	turkish: "	at (atlar)	",	source: "	Campus 1	/	Unité 3	"},
{french: "	La bibliothèque	",	turkish: "	kutuphane	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Embarquer	",	turkish: "	ucaga, gemiye binmek	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Sympa	",	turkish: "	nice,friendly	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Fêter	",	turkish: "	kutlamak, to celebrate	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Le théâtre	",	turkish: "	tiyatro	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Le compositeur	",	turkish: "	sarkiyi besteleyen	",	source: "	Campus 1	/	Unité 3	"},
{french: "	Situer	",	turkish: "	yerini belirlemek, to locate	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Un itinéraire	",	turkish: "	seyahat plani	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Jeter	",	turkish: "	firlatmak, cope atmak	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Cueillir	",	turkish: "	toplamak, to pick, to collect	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Végétal (f végétale, mpl végétaux)	",	turkish: "	bitki, sebze	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Fumer	",	turkish: "	sigara icmek	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Chasser	",	turkish: "	takip etmek, avlanmak	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Escalader	",	turkish: "	tirmanmak, to climb	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Le mur	",	turkish: "	duvar, the wall	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Exprimer	",	turkish: "	ifade etmek	",	source: "	Campus 1	/	Unité 4	"},
{french: "	La cohabitation	",	turkish: "	birlikte yasamak	",	source: "	Campus 1	/	Unité 4	"},
{french: "	C’est par la	",	turkish: "	orada, karsida, it’s over there	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Le bâtiment	",	turkish: "	bina	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Pres	",	turkish: "	yakin	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Loin	",	turkish: "	uzak	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Traverser	",	turkish: "	karsiya gecmek	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Le quai	",	turkish: "	rihtim, iskele, sokak	",	source: "	Campus 1	/	Unité 4	"},
{french: "	En face	",	turkish: "	onunde, in front	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Tout droit	",	turkish: "	dumduz, straight ahead	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Gauche	",	turkish: "	sol	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Droit	",	turkish: "	sag	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Suivre	",	turkish: "	takip etmek, follow	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Coureur, coureuse	",	turkish: "	yarismaci, racer	",	source: "	Campus 1	/	Unité 4	"},
{french: "	La traversée	",	turkish: "	gecit, crossing	",	source: "	Campus 1	/	Unité 4	"},
{french: "	à partir de	",	turkish: "	…’den itibaren	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Descendre	",	turkish: "	asagiya inmek	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Devant	",	turkish: "	onunde	",	source: "	Campus 1	/	Unité 4	"},
{french: "	à côté	",	turkish: "	yaninda, kiyisinda, near	",	source: "	Campus 1	/	Unité 4	"},
{french: "	au dessus	",	turkish: "	uzerinde, above	",	source: "	Campus 1	/	Unité 4	"},
{french: "	au milieu de	",	turkish: "	ortasinda, in the middle of	",	source: "	Campus 1	/	Unité 4	"},
{french: "	autour de	",	turkish: "	etrafindan, around	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Enfin	",	turkish: "	sonunda	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Nord, Sud	",	turkish: "	kuzey, guney	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Ouest, est	",	turkish: "	bati, dogu	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Un immeuble	",	turkish: "	bina	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Un logement	",	turkish: "	konaklama	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Ancien, modern	",	turkish: "	antik, modern	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Clair, sombre	",	turkish: "	aydinlik, karanlik	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Calme, bruyant	",	turkish: "	sessiz, gurultulu	",	source: "	Campus 1	/	Unité 4	"},
{french: "	La vue	",	turkish: "	gorus, manzara	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Neuf (f neuve), vieux (f vieille)	",	turkish: "	yeni, eski	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Le propriétaire	",	turkish: "	ev sahibi, owner, landlord	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Louer	",	turkish: "	kiralamak	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Le locataire	",	turkish: "	kiraci, tenant	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Un rez-de-chaussée	",	turkish: "	zemin kat, on the ground floor	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Le couloir	",	turkish: "	koridor	",	source: "	Campus 1	/	Unité 4	"},
{french: "	au fond du couloir	",	turkish: "	koridorun aşağısında, down the hall	",	source: "	Campus 1	/	Unité 4	"},
{french: "	en haut	",	turkish: "	yukarida, ustte	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Un escalier	",	turkish: "	merdiven, stairs	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Désordre	",	turkish: "	karisiklik, daginiklik	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Le cendrier	",	turkish: "	kulluk, ashtray	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Ranger	",	turkish: "	temizlemek, tidy up	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Se réveiller	",	turkish: "	uyanmak, wake up	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Se lever	",	turkish: "	kalkmak, get up	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Se coucher	",	turkish: "	uyumak, sleep	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Se laver	",	turkish: "	yikanmak	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Prendre le petit déjeuner	",	turkish: "	kahvalti yapmak	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Se préparer	",	turkish: "	hazirlanmak	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Se reposer	",	turkish: "	dinlenmek, to rest	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Se coucher	",	turkish: "	yataga gitmek, go to bed	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Dormir	",	turkish: "	uyumak, to sleep	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Tôt, tard	",	turkish: "	erken, gec, early, late	",	source: "	Campus 1	/	Unité 4	"},
{french: "	La négation	",	turkish: "	olumsuzluk	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Déjeuner	",	turkish: "	ogle yemegi yemek	",	source: "	Campus 1	/	Unité 4	"},
{french: "	S’habiller	",	turkish: "	giyinmek	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Diner	",	turkish: "	aksam yemegi yemek	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Le bassin	",	turkish: "	kucuk havuz	",	source: "	Campus 1	/	Unité 4	"},
{french: "	La chaussée	",	turkish: "	kaldirim, pavement	",	source: "	Campus 1	/	Unité 4	"},
{french: "	au rez-de-chaussée	",	turkish: "	zemin kat, on the ground floor	",	source: "	Campus 1	/	Unité 4	"},
{french: "	La boulangerie	",	turkish: "	firin, bakery	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Au milieu	",	turkish: "	ortasinda	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Au fond	",	turkish: "	basically	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Le côté	",	turkish: "	yan, kenar, side	",	source: "	Campus 1	/	Unité 4	"},
{french: "	ensoleillé	",	turkish: "	gunesli, sunny	",	source: "	Campus 1	/	Unité 4	"},
{french: "	Devenir	",	turkish: "	olmak, to become	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Revenir	",	turkish: "	geri gelmek, to come back	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Monter	",	turkish: "	tirmanmak, to climb	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Rester	",	turkish: "	kalmak, to stay	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Sortir	",	turkish: "	disari cikmak, to go out	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Venir	",	turkish: "	gelmek, to come	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Aller	",	turkish: "	gitmek, to go	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Naître	",	turkish: "	dogmak, to born	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Descendre	",	turkish: "	asagi inmek, to come down	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Entrer	",	turkish: "	girmek, to enter	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Rentrer	",	turkish: "	geri donmek, to return	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Tomber	",	turkish: "	dusmek, to fall	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Retourner	",	turkish: "	geri vermek, to return	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Arriver	",	turkish: "	varmak, to arrive	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Mourir	",	turkish: "	olmek, to die	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Partir	",	turkish: "	hareket etmek, to depart, to leave	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Passer	",	turkish: "	gecmek, to pass	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Une explication	",	turkish: "	aciklama, explanation	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Exprimer	",	turkish: "	aciklamak, dile getirmek, express	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Le doute	",	turkish: "	suphe, doubt	",	source: "	Campus 1	/	Unité 5	"},
{french: "	La certitude	",	turkish: "	kesinlik, certainty	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Un emploi	",	turkish: "	job	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Le temps passé	",	turkish: "	harcanan zaman	",	source: "	Campus 1	/	Unité 5	"},
{french: "	La disparition	",	turkish: "	gozden kaybolma, disappearance	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Raconter	",	turkish: "	soylemek, anlatmak, tell	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Le logiciel	",	turkish: "	yazilim, software	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Au fait	",	turkish: "	bu arada, by the way	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Rencontrer	",	turkish: "	bulusmak, meet	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Extract	",	turkish: "	cikarma	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Extraire	",	turkish: "	cikarmak	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Évidemment	",	turkish: "	obviously	",	source: "	Campus 1	/	Unité 5	"},
{french: "	La fusée	",	turkish: "	fuze, rocket	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Une orbite	",	turkish: "	yorunge, orbit	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Un satellite	",	turkish: "	uydu	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Détruire	",	turkish: "	yok etmek, to destroy	",	source: "	Campus 1	/	Unité 5	"},
{french: "	C'est bizarre ça !	",	turkish: "	That’s weird !	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Le concurrent	",	turkish: "	rakip	",	source: "	Campus 1	/	Unité 5	"},
{french: "	à reculons	",	turkish: "	geriye dogru, backwards	",	source: "	Campus 1	/	Unité 5	"},
{french: "	au sommet de	",	turkish: "	zirvesinde, at the top of	",	source: "	Campus 1	/	Unité 5	"},
{french: "	La détente	",	turkish: "	gevseme, relaxation	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Correspondre	",	turkish: "	eslesmek, to match	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Rencontrer	",	turkish: "	karilasmak, to meet	",	source: "	Campus 1	/	Unité 5	"},
{french: "	La rencontre	",	turkish: "	karsilasma, an encounter	",	source: "	Campus 1	/	Unité 5	"},
{french: "	 La forêt	",	turkish: "	orman, forest	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Je voudrais savoir … ?	",	turkish: "	question indirecte	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Le réseau	",	turkish: "	ag, web	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Consulter	",	turkish: "	danismak	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Télécharger	",	turkish: "	to download	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Le présentoir	",	turkish: "	ekran, display	",	source: "	Campus 1	/	Unité 5	"},
{french: "	Décrire	",	turkish: "	betimlemek, to describe	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Maîtriser	",	turkish: "	ustalasmak, to master	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Commander	",	turkish: "	siparis vermek, to order	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Absolument	",	turkish: "	kesinlikle, absolutely	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le cadeau	",	turkish: "	hediye, gift	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le réveil	",	turkish: "	calar saat, alarm clock	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Détester	",	turkish: "	neftret etmek, to hate	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Surtout	",	turkish: "	ozellikle, especially	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La montre	",	turkish: "	kol saati, watch	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Pas mal	",	turkish: "	fena degil, not bad	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Coûter	",	turkish: "	mal olmak, to cost	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Pas assez	",	turkish: "	yeterli degil, not enough	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Pourquoi pas ?	",	turkish: "	neden olmasin, why not ?	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Amusant	",	turkish: "	eglenceli, komik	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Bruyant	",	turkish: "	gurultulu, noisy	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Claire	",	turkish: "	net, aydinlik, clear, bright	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Travailleur	",	turkish: "	isci, worker	",	source: "	Campus 1	/	Unité 6	"},
{french: "	être fatigué	",	turkish: "	yorgun olmak, to be tired	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Payer en espèces	",	turkish: "	nakit odemek, pay in cash	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Avoir la monnaie	",	turkish: "	bozukluk olmasi, have the change	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Payer par carte de credit	",	turkish: "	kredi karti ile odemek	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Taper son code	",	turkish: "	sifresini girmek	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La couleur	",	turkish: "	renk, colour	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Blanc	",	turkish: "	beyaz, white	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Noir	",	turkish: "	siyah, black	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Pourpre	",	turkish: "	mor, purple	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Rouge	",	turkish: "	kirmizi, red	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Orange	",	turkish: "	turuncu, orange	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Jaune	",	turkish: "	sari, yellow	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Vert	",	turkish: "	yesil, green	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Bleu	",	turkish: "	mavi, blue	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Violet	",	turkish: "	menekse	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Rose	",	turkish: "	pembe, pink	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Kaki	",	turkish: "	haki, khaki	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Brun	",	turkish: "	kahverengi, brown	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Marron	",	turkish: "	kahverengi, brown	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Gris	",	turkish: "	gri, grey	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Bordeaux	",	turkish: "	bordo, 	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Peindre	",	turkish: "	boyamak, to paint	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Rond	",	turkish: "	yuvarlak	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Carre	",	turkish: "	kare	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Rectangulaire	",	turkish: "	dikdortgen	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Long, court	",	turkish: "	uzun, kisa	",	source: "	Campus 1	/	Unité 6	"},
{french: "	épais, mince	",	turkish: "	kalin, ince	",	source: "	Campus 1	/	Unité 6	"},
{french: "	large, étroite	",	turkish: "	genis, dar	",	source: "	Campus 1	/	Unité 6	"},
{french: "	haut, bas	",	turkish: "	yuksek, alcak	",	source: "	Campus 1	/	Unité 6	"},
{french: "	mesurer	",	turkish: "	olcmek	",	source: "	Campus 1	/	Unité 6	"},
{french: "	lourd, leger	",	turkish: "	agir, hafif	",	source: "	Campus 1	/	Unité 6	"},
{french: "	pèser	",	turkish: "	tartmak, to weight	",	source: "	Campus 1	/	Unité 6	"},
{french: "	le fauteuil	",	turkish: "	koltuk, armchair	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le collier	",	turkish: "	kolye	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La ceinture	",	turkish: "	kemer	",	source: "	Campus 1	/	Unité 6	"},
{french: "	en cuir	",	turkish: "	deriden yapilma	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le bracelet	",	turkish: "	bilezik	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La robe	",	turkish: "	elbise	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La tenue décontractée	",	turkish: "	casual outfit	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le pull	",	turkish: "	sweater	",	source: "	Campus 1	/	Unité 6	"},
{french: "	en laine	",	turkish: "	yunden yapilma, woolen	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le blouson	",	turkish: "	ceket	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le pantalon	",	turkish: "	pantalón	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La cravate	",	turkish: "	kravat	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le chemisier	",	turkish: "	bluz, blouse	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La jupe	",	turkish: "	etek	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le manteau	",	turkish: "	manto	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Un imperméable	",	turkish: "	yagmurluk, rain coat	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La chemise	",	turkish: "	gomlek, shirt	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La veste	",	turkish: "	takim elbise ceketi	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le costume	",	turkish: "	takim elbise, suit	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Les chaussettes	",	turkish: "	coraplar, socks	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Les chaussures	",	turkish: "	ayakkabilar, sh	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Les bottes	",	turkish: "	botlar	",	source: "	Campus 1	/	Unité 6	"},
{french: "	il est à la mode	",	turkish: "	moda olan	",	source: "	Campus 1	/	Unité 6	"},
{french: "	il est à la démodé	",	turkish: "	demode olan	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La taille	",	turkish: "	beden olcusu, size	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La pointure	",	turkish: "	ayakkabi numarasi, shoe size	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La soie	",	turkish: "	ipek, silk	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le velours	",	turkish: "	kadife, velvet	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La laine	",	turkish: "	yun, wool	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le coton	",	turkish: "	pamuk, coton	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le cuir	",	turkish: "	deri, leather	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le morceau	",	turkish: "	parca, piece	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Etre soif	",	turkish: "	susamak, to be thirsty	",	source: "	Campus 1	/	Unité 6	"},
{french: "	C’est pas mauvais !	",	turkish: "	fena degil	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le the	",	turkish: "	cay. tea	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le vin	",	turkish: "	sarap, vine	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le maïs	",	turkish: "	misir, corn	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La viande	",	turkish: "	et, meat	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le poisson	",	turkish: "	balik, fish	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La confiture	",	turkish: "	recel, jam	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le beurre	",	turkish: "	tereyagi, butter	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Un œuf	",	turkish: "	yumurta, egg	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le plat	",	turkish: "	tabak, plate	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le champignon	",	turkish: "	mantar, mushroom	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Assiette de crudités	",	turkish: "	sebze tabagi, vegetable platter	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le yaourt	",	turkish: "	yogurt	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le robinet	",	turkish: "	musluk, faucet	",	source: "	Campus 1	/	Unité 6	"},
{french: "	De l’eau du robinet	",	turkish: "	musluk suyu	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le riz	",	turkish: "	pilav, pirinc, rice	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Des côtelettes d'agneau	",	turkish: "	lamb chops	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La côtelette	",	turkish: "	parca, chop	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Un agneau	",	turkish: "	lamb	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Les haricots	",	turkish: "	fasulyeler, beans	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La langouste	",	turkish: "	istakoz, lobster	",	source: "	Campus 1	/	Unité 6	"},
{french: "	foie gras	",	turkish: "	kaz cigeri	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le sauté	",	turkish: "	sote	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Faire le fou	",	turkish: "	aptalca davranmak, being silly	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Se maquiller	",	turkish: "	makyaj yapmak, make up	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Se déguiser	",	turkish: "	kendini gizlemek, giyinmek, to disguise oneself, to dress up	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le concours	",	turkish: "	yarisma, competition	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La boule	",	turkish: "	top, ball	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le défilé	",	turkish: "	gecit toreni, parade	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le pourboire	",	turkish: "	bahsis, tip	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Laisser un pourboire	",	turkish: "	bahsis birakmak, leave a tip	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Demander l’addition	",	turkish: "	hesabi istemek	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Le serveur	",	turkish: "	garson, server	",	source: "	Campus 1	/	Unité 6	"},
{french: "	Se retrouver	",	turkish: "	bulusmak, to meet	",	source: "	Campus 1	/	Unité 6	"},
{french: "	La révélation	",	turkish: "	aciga vurrma, belirtme, ilham, esin	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Se tutoyer	",	turkish: "	senli benli olmak, be familiar with each other	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Vouvoyer	",	turkish: "	sizli bizli olmak	",	source: "	Campus 1	/	Unité 7	"},
{french: "	On peut aussi se tutoyer, non ?	",	turkish: "	We can also use informal terms, right?	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Raisonnable	",	turkish: "	mantikli	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Surtout pas	",	turkish: "	ozellikle hayir, especially not	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Personnellement	",	turkish: "	kisisel olarak, personally	",	source: "	Campus 1	/	Unité 7	"},
{french: "	La confidence	",	turkish: "	guven, confident	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Assez souvent	",	turkish: "	yeterince sik, often enough	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Utile	",	turkish: "	kullanislik, useful, helpful	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Les conseils	",	turkish: "	tavsiyeler, advices	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Offrir	",	turkish: "	teklif etmek, to offer	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Recevoir	",	turkish: "	almak, to receive	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Rendre	",	turkish: "	geri vermer, to return	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Prêter	",	turkish: "	odunc vermek, to lend	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Véritable	",	turkish: "	dogru, gercek, true, real	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Révèle	",	turkish: "	aciga cikma, revealed	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Indépendant	",	turkish: "	bagimsiz, independent	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Pessimiste	",	turkish: "	karamsar, pessimistic	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Intelligent	",	turkish: "	akilli, clever	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Patient / impatient	",	turkish: "	sabirli / sabirsiz	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Stable	",	turkish: "	dengeli, stable	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Paresseux	",	turkish: "	tembel, lazy	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Changeant	",	turkish: "	degisken, changing	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Courageux	",	turkish: "	cesur, brave	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Difficile à vivre	",	turkish: "	yasamasi zor, difficult to live	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Fier	",	turkish: "	gururlu, proud	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Sympathique	",	turkish: "	arkadasca, friendly	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Généreux	",	turkish: "	comert, generous	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Travailleur	",	turkish: "	caliskan, hard working	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Timide	",	turkish: "	utangac, shy	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Une allure	",	turkish: "	dis gorunus, apparence	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Etre beau	",	turkish: "	guzel olmak	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Etre laid	",	turkish: "	cirkin olmak	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Avoir un physique agréable	",	turkish: "	hos bir fizige sahip olmak, have a pleasant physique	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Avoir du charme	",	turkish: "	cekicilige sahip olmak, to have charm	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Être mince	",	turkish: "	ince olmak	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Être rond	",	turkish: "	yuvarlak olmak	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Maigre	",	turkish: "	zayif, skinny	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Gros	",	turkish: "	sisman	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Avoir un visage rond	",	turkish: "	yuvarlak bir yuzu olmak	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Avoir un visage allongé	",	turkish: "	uzun bir yuze sahip olmak	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Brun	",	turkish: "	kahverengi	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Chatain	",	turkish: "	dark blonde	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Blond	",	turkish: "	sarisin, blond	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Roux	",	turkish: "	kizil sacli, red hair	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Avoir les yeux (couleur)	",	turkish: "	(renk) gozlu olmak	",	source: "	Campus 1	/	Unité 7	"},
{french: "	La tête	",	turkish: "	kafa, head	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Le visage	",	turkish: "	yuz, face	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Un œil	",	turkish: "	goz, eye	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Les yeux	",	turkish: "	gozler	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Les cheveux	",	turkish: "	saclar, hair	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Le nez	",	turkish: "	burun, nose	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Une oreille	",	turkish: "	kulak, ear	",	source: "	Campus 1	/	Unité 7	"},
{french: "	La moustache	",	turkish: "	biyik	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Une dent	",	turkish: "	dis, tooth	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Les dents	",	turkish: "	disler, teeth	",	source: "	Campus 1	/	Unité 7	"},
{french: "	La bouche	",	turkish: "	agiz, mouth	",	source: "	Campus 1	/	Unité 7	"},
{french: "	La langue	",	turkish: "	dil, tongue	",	source: "	Campus 1	/	Unité 7	"},
{french: "	La barbe	",	turkish: "	sakal, beard	",	source: "	Campus 1	/	Unité 7	"},
{french: "	C’est ridicule !	",	turkish: "	bu sacmalik, it’s ridiculus	",	source: "	Campus 1	/	Unité 7	"},
{french: "	La vérité	",	turkish: "	gercek, truth	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Presque	",	turkish: "	neredeyse, almost	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Parfait	",	turkish: "	mukemmel, perfect	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Etre content	",	turkish: "	memnun olmak, be happy	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Le titre	",	turkish: "	baslik, title	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Compétent	",	turkish: "	yetkili, donanimli, qualified, capable	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Séduisant	",	turkish: "	cekici, goz alici, attractive, alluring	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Un journal d'opposition	",	turkish: "	muhalif, karsit goruslu gazete	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Une assiette	",	turkish: "	tabak, plate	",	source: "	Campus 1	/	Unité 7	"},
{french: "	La fourchette	",	turkish: "	catal, fork	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Le couteau	",	turkish: "	bicak, knife	",	source: "	Campus 1	/	Unité 7	"},
{french: "	La cuillère	",	turkish: "	kasik, spoon	",	source: "	Campus 1	/	Unité 7	"},
{french: "	La cuillère à café	",	turkish: "	cay kasigi, tea spoon	",	source: "	Campus 1	/	Unité 7	"},
{french: "	La tasse	",	turkish: "	kupa, fincan, cup	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Le verre	",	turkish: "	cam bardak	",	source: "	Campus 1	/	Unité 7	"},
{french: "	La serviette	",	turkish: "	yemek pecetesi, havlu, napkin, towel	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Bizarre	",	turkish: "	garip, weird, odd	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Folle	",	turkish: "	deli, crazy	",	source: "	Campus 1	/	Unité 7	"},
{french: "	S’intéresser	",	turkish: "	ilgili olmak, to be interested	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Embrasser	",	turkish: "	opmek, sarilmak, to kiss, to hug	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Vœux	",	turkish: "	wishes	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Le goût	",	turkish: "	tat, zevk, taste	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Tomber amoureux, euse de qn	",	turkish: "	birine asik olmak, fall in love with someone	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Avoir honte	",	turkish: "	utanmak, to be ashamed	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Triompher	",	turkish: "	zafer kazanmak, zafer, achieve a victory; be successful, great victory or achievement.	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Se moquer de qn	",	turkish: "	biriyle dalga gecmek, to make fun of someone	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Avoir peur	",	turkish: "	korkmak, to be afraid	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Passionnant	",	turkish: "	heyecan verici, exciting	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Amusant	",	turkish: "	eglenceli, amusing, funny	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Se marier	",	turkish: "	evlenmek, to get married	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Nommer	",	turkish: "	aday  olmak, to nominate	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Le poète	",	turkish: "	siir, poet	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Pas du tout	",	turkish: "	mumkun degil, no way, not at all	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Au contraire	",	turkish: "	aksine, on the contrary	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Se rappeler	",	turkish: "	hatirlamak, geri aramak, to remember, to call back	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Une humoriste	",	turkish: "	mizahci, sakaci, humorist	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Intelligente	",	turkish: "	akilli, clever	",	source: "	Campus 1	/	Unité 7	"},
{french: "	Une habitude	",	turkish: "	aliskanlik, habit	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Préciser	",	turkish: "	belirlemek, to specify	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Fragile	",	turkish: "	kirilgan	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Durer	",	turkish: "	surmek, to last	",	source: "	Campus 1	/	Unité 8	"},
{french: "	La connaissance	",	turkish: "	farkindalik, awareness	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Tout à coup	",	turkish: "	aniden, suddenly, all at once	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Être désert	",	turkish: "	terk edilmis olmak, to be deserted	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Le cri	",	turkish: "	ciglik, scream	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Marquer	",	turkish: "	isaretlemek, to mark, to score	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Le but	",	turkish: "	gol, goal	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Vers	",	turkish: "	e dogru, towards	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Lever	",	turkish: "	kaldirmak, to raise, to rise	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Être fier de qqn	",	turkish: "	biriyle gurur duymak, to be proud of someone	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Un itinéraire exemplaire	",	turkish: "	ornek yol, exemplary itinerary	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Un apprentissage	",	turkish: "	ogrenme, ciraklik, 	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Gentil	",	turkish: "	kibar	",	source: "	Campus 1	/	Unité 8	"},
{french: "	S’entraîner	",	turkish: "	pratik yapmak, to practice	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Participer	",	turkish: "	katilmak, katkida bulunmak	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Oublier	",	turkish: "	unutmak, to forget	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Un oncle	",	turkish: "	amca, dayi, uncle	",	source: "	Campus 1	/	Unité 8	"},
{french: "	La tante	",	turkish: "	hala, teyze, aunt	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Le neveu, la nièce	",	turkish: "	yegen, nephew	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Indifférent	",	turkish: "	kayitsiz, umursamaz, indifferent	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Ça fait longtemps	",	turkish: "	uzun zaman oldu, It's been a long time	",	source: "	Campus 1	/	Unité 8	"},
{french: "	La ferme	",	turkish: "	ciftlik, the farm	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Le village	",	turkish: "	koy, village	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Ça alors !	",	turkish: "	vay be, wow	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Pendant	",	turkish: "	boyunca, during	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Le maire	",	turkish: "	belediye baskani	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Une élection	",	turkish: "	secim, election	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Depuis	",	turkish: "	den beri, since, from	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Une enfance	",	turkish: "	cocukluk zamani, childhood	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Un voisin, une voisine	",	turkish: "	komsu, neighbour	",	source: "	Campus 1	/	Unité 8	"},
{french: "	S’ennuyer	",	turkish: "	sikilmak, to be bored	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Rarement	",	turkish: "	nadiren, rarely	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Une fois par semaine	",	turkish: "	haftada 1 kez, once a week	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Le bruit	",	turkish: "	gurultu, noise	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Un arbre	",	turkish: "	agac	",	source: "	Campus 1	/	Unité 8	"},
{french: "	La valeur	",	turkish: "	deger, value	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Le taureau	",	turkish: "	bull	",	source: "	Campus 1	/	Unité 8	"},
{french: "	S’installer	",	turkish: "	yerlesmek, to settle	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Une église	",	turkish: "	kilise	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Le palais	",	turkish: "	saray, palace	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Le spectacle	",	turkish: "	gosteri, the show	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Géant	",	turkish: "	devasa, giant	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Inoubliable	",	turkish: "	unutulmaz, unforgettable	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Le paysage	",	turkish: "	manzara, landscape	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Une époque	",	turkish: "	cag, era	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Construire	",	turkish: "	insa etmek, to build	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Le nageur	",	turkish: "	yuzucu, swimmer	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Heureusement	",	turkish: "	neyse ki, iyi ki, fortunately, happily, luckily, thankfully	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Exceptionnel	",	turkish: "	istisnai, exceptional	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Rénover	",	turkish: "	yenilemek, to renovate	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Transformer	",	turkish: "	donusturmek, to transform	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Une architecte	",	turkish: "	mimar, architecte	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Magique	",	turkish: "	sihirli, magic	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Une œuvre	",	turkish: "	sanat eseri, artwork	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Peu connue	",	turkish: "	az bilinen, little known	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Une exposition	",	turkish: "	sergi, exposition	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Une initiation	",	turkish: "	baslatma, initiation	",	source: "	Campus 1	/	Unité 8	"},
{french: "	D’abord	",	turkish: "	once, first of all	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Se coucher comme les poules	",	turkish: "	tavuk gibi erkenden uyumak	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Tout à fait	",	turkish: "	epeyce, kesinlikle, tamamiyle, quite, absolutely, fully	",	source: "	Campus 1	/	Unité 8	"},
{french: "	 Tout le monde	",	turkish: "	herkes, everybody	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Un agriculteur	",	turkish: "	farmer	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Le loisir	",	turkish: "	hobi, eglence, leisure	",	source: "	Campus 1	/	Unité 8	"},
{french: "	Cocher	",	turkish: "	tik atmak, to tick, to check	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Le journal	",	turkish: "	gazete, newspaper	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Diriger	",	turkish: "	yonetmek, isletmek, to direct, to manage, to run, to conduct	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Fabriquer	",	turkish: "	uretmek, to produce	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Gérer	",	turkish: "	yonetmek, ustesinden gelmek, to manage, to run, to operate	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Imprimer	",	turkish: "	basmak, to print	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Ajouter	",	turkish: "	eklemek, to add, to append	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Expédier	",	turkish: "	sevk etmek, gondermek, to dispatch, to send	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Manquer	",	turkish: "	kacirmak, ozlemek, basarisiz olmak, to miss, to fail	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Le roi	",	turkish: "	kral, king	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Pareil	",	turkish: "	the same, similar	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Un avion	",	turkish: "	ucak, plane	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Se développer	",	turkish: "	gelismek, buyumek, to grow, to develop, to thrive	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Le congé	",	turkish: "	tatil, izin, holiday, leave	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Une étoile	",	turkish: "	yildiz	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Un accueil	",	turkish: "	hosgeldin girisi, a welcome	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Être désolé, e	",	turkish: "	uzgun olmak, i am sorry	",	source: "	Campus 1	/	Unité 9	"},
{french: "	S'inquiéter	",	turkish: "	endiselenmek, to worry, to concern	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Être absent	",	turkish: "	eksik olmak, to be missing, to absent	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Lier	",	turkish: "	baglamak, to bind, to link, to attach, to fasten	",	source: "	Campus 1	/	Unité 9	"},
{french: "	D’abord, Ensuite, Puis, Alors, Tout à coup, Enfin	",	turkish: "	Önce, Sonra, Sonra, Sonra, Aniden, Sonunda, First, Next, Then, Then, Suddenly, Finally	",	source: "	Campus 1	/	Unité 9	"},
{french: "	En train de	",	turkish: "	surecinde, in the process of	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Ça y est !	",	turkish: "	iste bu ! That’s it !	",	source: "	Campus 1	/	Unité 9	"},
{french: "	 C'est une blague ou quoi ?	",	turkish: "	saka mi bu nedir ?, Is this a joke or what?	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Apporter	",	turkish: "	getirmek, to bring	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Le bénéfice	",	turkish: "	kazanc	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Recruter	",	turkish: "	ise almak, to recruit	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Rapidement	",	turkish: "	hizlica, quickly	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Convenir	",	turkish: "	uygun olmak, to suit, to admit, to agree with, to accept	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Être libre	",	turkish: "	musait olmak, bos olmak, to be free	",	source: "	Campus 1	/	Unité 9	"},
{french: "	La réunion	",	turkish: "	toplanti, meeting	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Apprécier	",	turkish: "	takdirle karsilanmak, to appreciate	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Des vertus curatives	",	turkish: "	iyilestirici ozellikler, healing properties	",	source: "	Campus 1	/	Unité 9	"},
{french: "	La curatives	",	turkish: "	iyilestirici	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Inventer	",	turkish: "	icat etmek, to invent	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Attendre	",	turkish: "	beklemek, to wait for, to expect	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Enterer	",	turkish: "	gommek, to bury	",	source: "	Campus 1	/	Unité 9	"},
{french: "	La chouette	",	turkish: "	baykus, owl	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Résoudre	",	turkish: "	cozmek, to solve, to resolve	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Un oiseau	",	turkish: "	kus, bird	",	source: "	Campus 1	/	Unité 9	"},
{french: "	La chasse	",	turkish: "	av, hunt	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Introuvable	",	turkish: "	bulunamayan, not found	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Le résultat	",	turkish: "	sonuc, result	",	source: "	Campus 1	/	Unité 9	"},
{french: "	La roue	",	turkish: "	tekerlek, wheel	",	source: "	Campus 1	/	Unité 9	"},
{french: "	La patinoire	",	turkish: "	buz pateni pisti	",	source: "	Campus 1	/	Unité 9	"},
{french: "	La voyante	",	turkish: "	kahin, seer	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Les oreillettes	",	turkish: "	kulakliklar, headset	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Un oranger	",	turkish: "	portakal agaci, orange tree	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Mensuel, le	",	turkish: "	aylik, monthly	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Un exemplaire	",	turkish: "	kopya, model, ornek, copy	",	source: "	Campus 1	/	Unité 9	"},
{french: "	Un administratif, une administrative	",	turkish: "	yonetim, administrator	",	source: "	Campus 1	/	Unité 9	"},
{french: "	La publicité	",	turkish: "	reklam, advertisement	",	source: "	Campus 1	/	Unité 9	"},
{french: "	La comparaison	",	turkish: "	karsilastirma, comparison	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La ressemblance	",	turkish: "	benzerlik, resemblance	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La supposition	",	turkish: "	tahmin, guess	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La spacieuse	",	turkish: "	genis, ferah, spacious	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La langouste	",	turkish: "	istakoz, lobster	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le lapin	",	turkish: "	tavsan, rabbit	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La moutarde	",	turkish: "	hardal, mustard	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La distraction	",	turkish: "	dikkat daginikligi	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Freiner	",	turkish: "	fren yapmak, to brake	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Rouler	",	turkish: "	yuvarlanmak, yol almak, to roll	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Ne verbe que	",	turkish: "	sadece, only	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Seulement	",	turkish: "	sadece, only	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Hésiter	",	turkish: "	tereddut etmek, to hesitate	",	source: "	Campus 1	/	Unité 10	"},
{french: "	d'un côté, ... et d'un autre côté	",	turkish: "	bir tarafta... ve diğer tarafta, on one side, ... and on the other side	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Accueillir	",	turkish: "	hos karsilamak, to welcome	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Accueillant	",	turkish: "	hos karsilayan. Welcoming, friendly	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Sauf	",	turkish: "	without	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Plus grand que	",	turkish: "	den buyuk	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Moins grand que	",	turkish: "	den daha az buyuk	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Aussi grand que	",	turkish: "	e kadar buyuk, ayni buyuklukte	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Bon, meilleur, le meilleur	",	turkish: "	good, better, the best	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Bien, mieux, le meilleur	",	turkish: "	good, better, the best 	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Mauvais, pire, le pire	",	turkish: "	bad, worse, the worst	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Plus d’habitant à Marseille que	",	turkish: "	Marseille’de daha fazla ikamet eden var	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Moins d’habitant à Marseille que	",	turkish: "	Marseille’de daha az ikamet eden var	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Autant d’habitant à Marseille que	",	turkish: "	Marseille’de ayni miktarda ikamet eden var	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Pierre travaille plus que Juliette	",	turkish: "	Pierre, Juliette’ten daha fazla calisiyor	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Pierre travaille moins que Juliette	",	turkish: "	Pierre, Juliette’ten daha az calisiyor	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Pierre travaille autant que Juliette	",	turkish: "	Pierre, Juliette’ten ayni miktarda calisiyor	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Maudit	",	turkish: "	lanetli, damn, cursed	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Se ressembler	",	turkish: "	birbirine benzemek, to resemble	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La manière	",	turkish: "	yol, yon, sekil, the way	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La commune	",	turkish: "	sehir, town	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Fonctionnaires	",	turkish: "	resmi gorevli, officer	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le médicament	",	turkish: "	ilac, medication	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Rembourser	",	turkish: "	geri odemek, to repy, to reimburse, to refund	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Déranger	",	turkish: "	rahatsiz etmek, to disturb	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Transporter	",	turkish: "	tasimak, to transport	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Emporter	",	turkish: "	goturmek, to carry, to take away	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Si	",	turkish: "	eger, if	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Bouger	",	turkish: "	hareket etmek, to move	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Frapper	",	turkish: "	vurmak, to hit	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le conférencier	",	turkish: "	konusmaci, speaker	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Accompagner	",	turkish: "	eslik etmek, to accompany, to go with	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Amener	",	turkish: "	getirmek, to bring	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Emmener	",	turkish: "	goturmek, to drive, to take away	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Confondre	",	turkish: "	kafa karistirmak, to confuse, to mix	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Apporter	",	turkish: "	getirmek, to bring	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La valise	",	turkish: "	valiz, baggage	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Lourde	",	turkish: "	agir, heavy	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Discuter	",	turkish: "	tartismak, to discuss	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Convaincre	",	turkish: "	ikna etmek, to convince, to persuade	",	source: "	Campus 1	/	Unité 10	"},
{french: "	à partir de	",	turkish: "	den itibaren, from	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Quel temps fait-il ?	",	turkish: "	what is the weather ?	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Quel temps fera-t-il demain ?	",	turkish: "	what will the weather be tomorrow ?  	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Ensoleillé	",	turkish: "	gunesli, sunny	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La moitié	",	turkish: "	yarim, half	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Douce	",	turkish: "	kibar, nazik, gentle	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Nuageux	",	turkish: "	bulutlu, cloudy	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La pluie	",	turkish: "	yagmur, rain	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Pleuvoir	",	turkish: "	yagmur yagmasi, to rain	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La neige	",	turkish: "	kar, snow	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Neiger	",	turkish: "	to snow	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le vent	",	turkish: "	ruzgar, wind	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Un orage	",	turkish: "	firtina, storm	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La météo	",	turkish: "	hava durumu, weather 	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La prévision	",	turkish: "	tahmin, ongoru, forecast	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La prévision météorologique	",	turkish: "	hava durumu ongorusu	",	source: "	Campus 1	/	Unité 10	"},
{french: "	il fait chaud	",	turkish: "	hava sicak, it is hot	",	source: "	Campus 1	/	Unité 10	"},
{french: "	il fait bon	",	turkish: "	hava guzel, it is good	",	source: "	Campus 1	/	Unité 10	"},
{french: "	il fait froid	",	turkish: "	hava soguk, it is cold	",	source: "	Campus 1	/	Unité 10	"},
{french: "	il gèle	",	turkish: "	hava dondurucu soguk, it is freezing	",	source: "	Campus 1	/	Unité 10	"},
{french: "	il fait moins dix degrés	",	turkish: "	hava eksi 10 derece, it is mines 10 degree	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La colline	",	turkish: "	tepe, hill	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le sommet	",	turkish: "	zirve, sommet	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La plaine	",	turkish: "	ova, plain	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La vallée	",	turkish: "	vadi. valley	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La rivière	",	turkish: "	nehir, river	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La fleuve	",	turkish: "	akarsu, river	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le lac	",	turkish: "	gol, lake	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La cascade	",	turkish: "	selale, waterfall	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La mer	",	turkish: "	deniz, sea	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Un océan	",	turkish: "	okyanus, ocean	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La plage	",	turkish: "	sahil, beach	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La forêt	",	turkish: "	orman, forest	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La fleur	",	turkish: "	cicek, flower	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le climat	",	turkish: "	iklim, climate	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le palmarès	",	turkish: "	odul listesi	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Variés	",	turkish: "	cesitli, varied	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La particularité	",	turkish: "	ozellik, particularity, feature	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Une émission	",	turkish: "	radyo, tv pprogrami, show	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Un auteur	",	turkish: "	yazar, author	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le joueur	",	turkish: "	oyuncu, player	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Réussir	",	turkish: "	basarmak, succeed	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Une épreuve	",	turkish: "	test, deneme, kanit, test, trial, proof	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Amusant	",	turkish: "	eglenceli, komik	",	source: "	Campus 1	/	Unité 10	"},
{french: "	inattendu	",	turkish: "	beklenmedik. unexpected	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Attirer	",	turkish: "	cezbetmek, to attract	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La fantaisie	",	turkish: "	fantazi	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Un humoriste	",	turkish: "	mizahci, humorist	",	source: "	Campus 1	/	Unité 10	"},
{french: "	intimiste	",	turkish: "	samimi, intimate	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le prisonnier, la prisonnière	",	turkish: "	mahkum, prisoner	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La célébrité	",	turkish: "	unlu, celebrity	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La tradition	",	turkish: "	gelenek, tradition	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Découvrir	",	turkish: "	kesfetmek, discover	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Explorer	",	turkish: "	kesfetmek, explore	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le commissaire	",	turkish: "	komiser, commissioner	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Rencontrer	",	turkish: "	karsilasmak, tecrube edinmek, yuzlesmek, to meet, to experience, to face	",	source: "	Campus 1	/	Unité 10	"},
{french: "	C’est rassurant.	",	turkish: "	bu guven verici, it’s reassuring	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le métier	",	turkish: "	is, job	",	source: "	Campus 1	/	Unité 10	"},
{french: "	C’est la recette de succès.	",	turkish: "	basarinin recetesi budur., This is the recipe for success.	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Un avenir	",	turkish: "	gelecek, futur	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le milliardaire	",	turkish: "	milyarder, billionaire	",	source: "	Campus 1	/	Unité 10	"},
{french: "	étonner	",	turkish: "	afallatmak, sasirtmak, to astonish, to surprise	",	source: "	Campus 1	/	Unité 10	"},
{french: "	étonnant	",	turkish: "	sasirtici, inanilmaz, amazing, surprising	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le téléviseur, la télé	",	turkish: "	televizyon, television	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Un écran	",	turkish: "	ekran, screen	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La télécommande	",	turkish: "	uzaktan kumanda, remote	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Changer de chaîne	",	turkish: "	kanali degistirmek, change the channel	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La chaîne	",	turkish: "	televizyon kanali, channel	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La station de radio	",	turkish: "	radyo istasyonu, radio station	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Capter	",	turkish: "	secmek, toplamak, esir almak, to pick up, to receive, to capture	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Une antenne	",	turkish: "	anten	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le satellite	",	turkish: "	uydu, satellite	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le câble	",	turkish: "	kablo, cable	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Puissant	",	turkish: "	guclu, strong, powerful	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le devoir	",	turkish: "	ev odevi, homework	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Aller chercher	",	turkish: "	gidip getirmek, to fetch 	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Être faible	",	turkish: "	zayif olmak, to be weak	",	source: "	Campus 1	/	Unité 10	"},
{french: "	En début de	",	turkish: "	baslangicinda, at the beginning of	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Une enquête	",	turkish: "	sorusturma, investigation	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Intellectuel	",	turkish: "	entellektuel,intellectual	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Déprimant	",	turkish: "	ic karartici, depressing	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Extraordinaire	",	turkish: "	siradisi, extraordinary	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Un endroit	",	turkish: "	yer, nokta, alan, place, spot, point	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Se ressembler	",	turkish: "	birbirine benzemek, to look alike, to resemble	",	source: "	Campus 1	/	Unité 10	"},
{french: "	C’est génial.	",	turkish: "	bu harika. it’s awesome.	",	source: "	Campus 1	/	Unité 10	"},
{french: "	La balade en montagne	",	turkish: "	dag yuruyusu, mountain walk	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Le paysage	",	turkish: "	manzara, landscape, scenery	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Au bord de la mer	",	turkish: "	deniz kenarinda, at the seaside	",	source: "	Campus 1	/	Unité 10	"},
{french: "	Quotidien	",	turkish: "	gunluk, daily	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Hebdomadaire	",	turkish: "	haftalik, weekly	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Mensuel	",	turkish: "	aylik, monthly	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Annuel	",	turkish: "	yillik, yearly	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le chômeur	",	turkish: "	issiz, unemployed	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Résoudre	",	turkish: "	cozmek, to solve	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La rubrique	",	turkish: "	makale, bolum, section	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Les petites annonces	",	turkish: "	kucuk ilanlar, classifieds	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La destruction	",	turkish: "	yikim, destruction	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La violence	",	turkish: "	siddet, violence	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Influencer	",	turkish: "	etkilemek, to influence	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le chasseur	",	turkish: "	avci, hunter	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le tabac	",	turkish: "	tutun mamulleri, tobacco	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Une association	",	turkish: "	dernek, association, organization	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Un débat	",	turkish: "	tartisma, debate	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Dirigeant, dirigeante	",	turkish: "	yoneten, iktidar partisi, leader, ruler	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Se moquer	",	turkish: "	alay etmek, umursamamak, to mock, not care about	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Nos dirigeant se moquent de l'environnement.	",	turkish: "	Our leaders don't care about the environment.	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Lentement	",	turkish: "	yavasca, slowly	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Calmement	",	turkish: "	sakince, calmly	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Tu dois donner l'image d'une femme sûre d'elle.	",	turkish: "	You must give the image of a confident woman.	",	source: "	Campus 1	/	Unité 11	"},
{french: "	En face de qqn	",	turkish: "	birinin onunde, in front of someone	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Regarde-le avec assurance	",	turkish: "	look at him with confidence	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Une agressivité	",	turkish: "	saldirganlik, aggressiveness	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Poli	",	turkish: "	kibar, polite	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Poliment	",	turkish: "	kibar bir sekilde, politely	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Abandonner	",	turkish: "	ayrilmak, vazgecmek, terketmek, to give up, to abandon, to leave	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Se sentir mal	",	turkish: "	kotu hissetmek, to feel bad	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Avoir mal à la tête	",	turkish: "	bas agrisi olmak, have headache	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La douleur	",	turkish: "	agri, aci, pain	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le dos	",	turkish: "	arka, sirt, back	",	source: "	Campus 1	/	Unité 11	"},
{french: "	J'ai des douleurs là, dans le dos.	",	turkish: "	I have pain there, in my back.	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le trac	",	turkish: "	sahne korkusu, stage fright	",	source: "	Campus 1	/	Unité 11	"},
{french: "	J’ai des vertiges	",	turkish: "	basi donmek. I feel dizzy.	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Sonner	",	turkish: "	zil calmak, to ring	",	source: "	Campus 1	/	Unité 11	"},
{french: "	évidemment	",	turkish: "	acikca, belli ki, apacik, obviously	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Render	",	turkish: "	geri vermek, iade etmek, to give back, to render, to return	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Fumer	",	turkish: "	sigara icmek, to smoke	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Une altitude	",	turkish: "	yukseklik, rakim, altitude	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le bois	",	turkish: "	odun, wood	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le corps	",	turkish: "	vucut, body	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La santé	",	turkish: "	saglik, health	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La maladie	",	turkish: "	hastalik, disease	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Être malade	",	turkish: "	hasta olmak, be sick	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Avoir une maladie	",	turkish: "	hastaligi olmak, have an illness	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le rhume	",	turkish: "	soguk alginligi, cold	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La grippe	",	turkish: "	grip, flu	",	source: "	Campus 1	/	Unité 11	"},
{french: "	C’est grave	",	turkish: "	bu ciddi, it’s serious	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Ce n’est pas grave	",	turkish: "	ciddi degil, it’s not serious	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Avoir mal au dos, a la tête, aux pieds	",	turkish: "	sirtinda, basinda, ayaginda agrisi olmak, having back pain, head pain, foot pain	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Un accident	",	turkish: "	kaza, accident	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Se casser la jambe	",	turkish: "	bacagini kirmak, to break a leg	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Se blesser	",	turkish: "	kanamak, yaralanmak, to blood, to wound, to hurt	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Se faire mal	",	turkish: "	kendine zarar vermek, to hurt one’s self	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le médecin, le docteur	",	turkish: "	doktor, doctor	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le dentiste	",	turkish: "	dis hekimi, dentist	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Faire une ordonnance	",	turkish: "	recete yazmak, to write a prescription	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Une ordonnance	",	turkish: "	recete, prescription	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La pharmacie	",	turkish: "	eczane, pharmacy	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Prendre un médicament	",	turkish: "	ilac almak, to take pill, medication	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Se soigner	",	turkish: "	kendine iyi bak, to take care of oneself	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Un hôpital	",	turkish: "	hastane, hospital	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Guérir	",	turkish: "	iyilesmek, to heal, to recover	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La tête	",	turkish: "	bas, kafa, head	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La main	",	turkish: "	el, hand	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le doigt	",	turkish: "	parmak, finger	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le bras	",	turkish: "	kol, arm	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le cou	",	turkish: "	boyun, neck	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Une épaule	",	turkish: "	omuz, shoulder	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le ventre	",	turkish: "	karin, gobek, belly, stomach	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La jambe	",	turkish: "	bacak, leg	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le pied	",	turkish: "	ayak	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Obligatoire	",	turkish: "	zorunlu, mandatory	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Rembourser	",	turkish: "	geri odemek, to pay back	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Complémentaire	",	turkish: "	tamamlayici olarak, complementary, additional, supplementary	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Une opération	",	turkish: "	ameliyat, operation	",	source: "	Campus 1	/	Unité 11	"},
{french: "	En cas de	",	turkish: "	olursa diye, … durumunda, in case of	",	source: "	Campus 1	/	Unité 11	"},
{french: "	En cas d’urgence	",	turkish: "	acciliyet durumunda, in case of emergency	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le pompier	",	turkish: "	itfayeci, firefighter	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Grave	",	turkish: "	ciddi, sert siddetli, severe, serious,	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Être en retard	",	turkish: "	gec kalmak, to be late	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Avoir le droit de faire	",	turkish: "	birseyi yapmaya yetkisi olmak, have the right to do	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Je n’ai pas le droit de vous laisser entrer	",	turkish: "	Sizi içeri almaya yetkim yok, I have no right to let you in	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Se dépêcher	",	turkish: "	acele etmek, to hurry up	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Descendre	",	turkish: "	asagi inmek, arabadan inmek, to come down, to get off	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Se débrouiller	",	turkish: "	idare etmek, yonetmek, to get by, to manage	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Garer	",	turkish: "	park etmek, to park	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Interdire à qqn de faire qqch	",	turkish: "	birinin bir sey yapmasini yasaklamak, to forbid someone from doing something	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Défendre à qqn de faire qqch	",	turkish: "	birinin bir sey yapmasini yasaklamak, to forbid someone from doing something	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Conseiller	",	turkish: "	ogut vermek, tavsiye vermek, to advise	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Autoriser qqn à faire qqch	",	turkish: "	birinin birsey yapmasina izin vermek, to allow someone to do something	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Permettre à qqn de faire qqch	",	turkish: "	birinin birsey yapmasina izin vermek, to allow someone to do something	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Demander une autorisation	",	turkish: "	izin istemek, yetki istemek, to request autorization	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Souhaiter	",	turkish: "	istemek, dilemek, to wish, to hope	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Déménager	",	turkish: "	tasinmak, to relocate, to move	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Solliciter	",	turkish: "	rica etmek, to solicit, to ask	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Absenter	",	turkish: "	olmamak, to be absent	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Une aventure	",	turkish: "	macera, adventure	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Sauf	",	turkish: "	haric, disinda, except, unless	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Répondre	",	turkish: "	cevap vermek, to answer, to reply, to respond	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La devise de	",	turkish: "	nin slogani, the motto of	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Solidarité	",	turkish: "	dayanisma, solidarity	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Honneur	",	turkish: "	onur, honor	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La commune	",	turkish: "	belediye	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le ministre	",	turkish: "	bakan, minister	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Un maire	",	turkish: "	belediye baskani	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le député	",	turkish: "	milletvekili	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le loi	",	turkish: "	kanun, law	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Orienter	",	turkish: "	yonlendirmek	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Voter	",	turkish: "	oy kullanmak, to vote	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Nommer	",	turkish: "	aday gostermek, to nominate	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Siéger	",	turkish: "	oturmak, to sit	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le cambrioleur	",	turkish: "	hirsiz, burglar, thief, house breaker	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Le coffre-fort	",	turkish: "	kasa, safe	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Attentif	",	turkish: "	dikkatli, ozenli, attentive, careful, watchful	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Prudent	",	turkish: "	dikkatlice, akillica, careful, wise, safe	",	source: "	Campus 1	/	Unité 11	"},
{french: "	élire	",	turkish: "	secmek, to elect	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Être en grève	",	turkish: "	grevde olmak, to be on strike	",	source: "	Campus 1	/	Unité 11	"},
{french: "	Se réunir	",	turkish: "	bulusmak, toplanmak, to meet, to get together, to assemble	",	source: "	Campus 1	/	Unité 11	"},
{french: "	La bande dessinée	",	turkish: "	cizgi roman, comics	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Etre apprécié	",	turkish: "	takdir edilmek, to be appreciated	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Sauvage	",	turkish: "	vahsi, wild	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le lion, la lionne	",	turkish: "	aslan, lion	",	source: "	Campus 1	/	Unite 12	"},
{french: "	La girafe	",	turkish: "	zurafa, giraffe	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Un éléphant, une éléphante	",	turkish: "	fil, An elephant, a female elephant	",	source: "	Campus 1	/	Unite 12	"},
{french: "	En plain	",	turkish: "	tam ortasinda, right in the middle	",	source: "	Campus 1	/	Unite 12	"},
{french: "	La conquête	",	turkish: "	fetih, conquest	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Conquérir	",	turkish: "	fethetmek, to conquer	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Je rêve ou quoi !	",	turkish: "	hayal mi goruyorum, nedir ! Am I dreaming !	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Ça fait combien de temps qu’on ne s’est pas vus ?	",	turkish: "	How long has it been since we last saw each other?	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Etre satisfait	",	turkish: "	memnun olmak, to be satisfied	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Décevoir	",	turkish: "	hayal kirikligina ugratmak, to disappoint, to deceive	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Etre déçu	",	turkish: "	hayal kirikligina ugramak, being disappointed	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Deception	",	turkish: "	hayal kirikligi, disappointment	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Je suis déçu par mes collègues.	",	turkish: "	I am disappointed in my colleagues.	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le dommage	",	turkish: "	utanc verici, yazik, shame, pity	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Tant pis	",	turkish: "	cok kotu, too bad	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Tant mieux	",	turkish: "	so much the better	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Formidable	",	turkish: "	harika, muazzam, wonderful, tremendous, terrific	",	source: "	Campus 1	/	Unite 12	"},
{french: "	La peur	",	turkish: "	korku, fear	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le coureur	",	turkish: "	kosucu, runner	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Renverser	",	turkish: "	dokmek, to spill	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Gagner à la loterie	",	turkish: "	loto kazanmak, to win the lottery	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Ça m’est égal.	",	turkish: "	umurumda degil, I don’t care	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Ça ne fait rien.	",	turkish: "	it doesn’t matter, onemli degil	",	source: "	Campus 1	/	Unite 12	"},
{french: "	J’ai honte de vous	",	turkish: "	sizden utaniyorum, I’m ashamed of you.	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Attacher la ceinture	",	turkish: "	kemerini baglamak, to fasten the belt	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Démarrer	",	turkish: "	baslamak, to start, to kick off	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Composter le billet	",	turkish: "	bileti isaretlemek	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Décoller	",	turkish: "	cikarmak, ucagin havalandirmak, to take off, to fly off	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le décollage	",	turkish: "	havalanma, take-off, lift-off	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Atterrir	",	turkish: "	ucagi indirmek, to land, to touch down	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Un atterrissage	",	turkish: "	ucagin inmesi, landing	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Débarquer	",	turkish: "	yuku bosaltmak, to unload, to disembark	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Embarque	",	turkish: "	yuklemek, to load	",	source: "	Campus 1	/	Unite 12	"},
{french: "	La douane	",	turkish: "	gumruk, customs	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Faire le plan d’essence	",	turkish: "	yakit plani yapmak, to make the fuel plan	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le poste de péage	",	turkish: "	gecis gisesi, toll booth	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Tomber sur un répondeur	",	turkish: "	telesekretere dusmek, 	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Côté couloir	",	turkish: "	koridor kenari, aisle seat	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Côté fenêtre	",	turkish: "	pencere kenari, window seat	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Une aire de repos de l'autoroute	",	turkish: "	otoyol dinlenme alani, a highway rest area	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Magnifique	",	turkish: "	harika, muhtesem, magnificent	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Réparer	",	turkish: "	tamir etmek, restore etmek, yenilemek, to fix, to repair, to restore	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le toit	",	turkish: "	cati, roof	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Construire	",	turkish: "	insa etmek, to build	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le mur	",	turkish: "	duvar, wall	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le bricolage	",	turkish: "	kendin yap, do it yourself	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le sigle	",	turkish: "	kisaltma, acronym	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le tapis	",	turkish: "	hali, carpet	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le roi	",	turkish: "	kral, king	",	source: "	Campus 1	/	Unite 12	"},
{french: "	La reine	",	turkish: "	kralice, queen	",	source: "	Campus 1	/	Unite 12	"},
{french: "	La fève	",	turkish: "	fasulye, bean	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le lecteur	",	turkish: "	okuyucu, reader	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Se dérouler	",	turkish: "	acilmak, gerceklesmek, meydana gelmek, to unfold, to take place	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le lauréat, la laureate	",	turkish: "	kazanan, winner	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Maladroit	",	turkish: "	sakar, clumsy	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Inventif	",	turkish: "	yaratici, inventive, creative	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Se suicider	",	turkish: "	intihar etmek, to suicide	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Ignoble	",	turkish: "	asagilik, igrenc, rezil, vile, despicable, shameful	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le secret	",	turkish: "	sir, gizem, secret	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le pont	",	turkish: "	kopru, bridge	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Confondre	",	turkish: "	kafasi karismak, to confuse	",	source: "	Campus 1	/	Unite 12	"},
{french: "	La tente	",	turkish: "	cadir, tent	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Loger	",	turkish: "	yerlesmek, to accommodate	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Minceur	",	turkish: "	zayiflamak, slimming, thinness	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le portefeuille	",	turkish: "	cuzdan, walllet	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Loger	",	turkish: "	yerlesmek, to accommodate	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Minceur	",	turkish: "	zayiflamak, slimming, thinness	",	source: "	Campus 1	/	Unite 12	"},
{french: "	Le portefeuille	",	turkish: "	cuzdan, walllet	",	source: "	Campus 1	/	Unite 12	"},
];
